
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was org.generated by Apache CXF 2.7.10
 * 2014-03-03T11:43:03.812+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsrf/r-2")
public class ResourceUnknownFault extends Exception {
    
    private org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType resourceUnknownFault;

    public ResourceUnknownFault() {
        super();
    }
    
    public ResourceUnknownFault(String message) {
        super(message);
    }
    
    public ResourceUnknownFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceUnknownFault(String message, org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType resourceUnknownFault) {
        super(message);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public ResourceUnknownFault(String message, org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType resourceUnknownFault, Throwable cause) {
        super(message, cause);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType getFaultInfo() {
        return this.resourceUnknownFault;
    }
}
