
package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-03T11:23:48.397+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableTerminationTimeFault extends Exception {
    
    private org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault;

    public UnacceptableTerminationTimeFault() {
        super();
    }
    
    public UnacceptableTerminationTimeFault(String message) {
        super(message);
    }
    
    public UnacceptableTerminationTimeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnacceptableTerminationTimeFault(String message, org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault) {
        super(message);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public UnacceptableTerminationTimeFault(String message, org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault, Throwable cause) {
        super(message, cause);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType getFaultInfo() {
        return this.unacceptableTerminationTimeFault;
    }
}
